CREATE TABLE band(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT,
  CREATE_DATE DATE NOT NULL,
  DATE_BAND DATE NOT NULL,
  DAY INT,
  MONTH VARCHAR(3),
  YEAR INT,
  NAME_BAND VARCHAR(255) collate utf8_unicode_ci default NULL,
  START_TIME TIME NOT NULL,
  END_TIME TIME NOT NULL,
  COUNT_HOURS INT,
  PRICE INT,
  COMMENT VARCHAR(255) collate utf8_unicode_ci default NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC
  ENGINE InnoDB;

